server:
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true


spring:
  ai:
    dashscope:
      api-key: sk-ws-H.PMPLELM.4SZm.MEQCICrWkumM7FKYq2PGINGBPaoFh3N5HGpkinxO_MG2ZQO7AiBx0QhPBuhs3PDy2wEMOeDZBiInFuUVTM0na2JDDaQgVQ
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: deepseek-v3
  data:
    redis:
      host: localhost
      database: 1
      port: 6379


